### ISSUE TITLE
[1.5] Post install error message

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1037]
```
Fatal error: Uncaught exception 'ReflectionException' with message 'Class MU\YourCityModule\Container\LinkContainer does not exist' in /domain/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php:150 

Stack trace: #0 /domain/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php(150): ReflectionClass->__construct('MU\\YourCityModu...') 

#1 /domain/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php(90): Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator->validateClass('Zikula\\Core\\Lin...', 'MU\\YourCityModu...') 

#2 /domain/vendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php(80): Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator->validateDefinitionArgument('Zikula\\Core\\Lin...', Object(Symfony\Component\DependencyInjection\Definition)) 

#3 /domain/vendor/matthiasno in /domainvendor/matthiasnoback/symfony-service-definition-validator/ArgumentValidator.php on line 150
```

**Comment by Portugao** [comment]
Calling the extensions gives the same error.

**Comment by Portugao** [comment]
My fault. I can close it; sorry.
