### ISSUE TITLE
Class error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1076]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | 0.7.4
| Operating System       | Windows
| Zikula Target in Model | ZK15DEV
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
Install of the module and redirect to the extension list

### Actual behavior
I get this error:
```
Fatal error: Class 'Zikula\Bundle\HookBundle\Category\UiHooksCategory' not found in F:\Arbeit\XAMPP\htdocs\zik15\modules\MU\BloggingModule\Container\Base\AbstractHookContainer.php on line 32

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(C:\$Recycle.Bin\S-1-5-18,C:\$Recycle.Bin\S-1-5-18): Zugriff verweigert (code: 5)' in F:\Arbeit\XAMPP\htdocs\zik15\vendor\symfony\symfony\src\Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler.php:148 Stack trace: #0 [internal function]: RecursiveDirectoryIterator->__construct('C:\\$Recycle.Bin...', 4096) #1 F:\Arbeit\XAMPP\htdocs\zik15\vendor\symfony\symfony\src\Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler.php(148): RecursiveDirectoryIterator->getChildren() #2 F:\Arbeit\XAMPP\htdocs\zik15\vendor\symfony\symfony\src\Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler.php(117): Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->findClassInPath(false, 'UiHooksCategory', 'ZikulaSecurityC...') #3 F:\Arbeit\XAMPP\htdocs\zik15\vendor\symfony\symfony\src\Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler. in F:\Arbeit\XAMPP\htdocs\zik15\vendor\symfony\symfony\src\Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler.php on line 148
```

### Steps to reproduce
Take the actual repository of Blogging (https://github.com/Portugao/Blogging) and try to install.

**Comment by Portugao** [comment]
Try to recheck and report result.

**Comment by craigh** [comment]
is your 1.5 up to date? try to pull from github again

**Comment by Portugao** [comment]
I do

**Comment by Guite** [comment]
Closing as it should work with newest core git revision. Feel free to reopen otherwise.

**Comment by Portugao** [comment]
Sorry. Works indeed.
I should know, that is important to have an actual core.
