### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#1091]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | 0.7.5 staging update
| Operating System       | Windows
| Zikula Target in Model | ZK14
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
when I want to change a property I should be able directly to click at a checkbox

### Actual behavior
when I click on a property checkbox an error is displayed in the message window and nothing changed in the checkbox. If I click a second time everything is working like expected. As long as I do not change the field I have to work with I can change inside the Properties what I want. As soon when I move to another Field I do have again the message.

It looks like a click inside the properties window is needed to get the focus on that window.

here is the message:
````
null
org.eclipse.ui
Error
Sat Jul 29 19:18:51 CEST 2017
Unhandled event loop exception

org.eclipse.swt.SWTError: Item not added
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.ToolBar.createItem(ToolBar.java:396)
	at org.eclipse.swt.widgets.ToolItem.<init>(ToolItem.java:128)
	at org.eclipse.jface.action.Separator.fill(Separator.java:61)
	at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:343)
	at de.guite.modulestudio.ui.views.ViewCustomiser.customiseLogView(ViewCustomiser.xtend:114)
	at de.guite.modulestudio.ui.views.ViewCustomiser.changeDefaultViews(ViewCustomiser.xtend:45)
	at de.guite.modulestudio.ui.sirius.SiriusSelectionListener.selectionChanged(SiriusSelectionListener.xtend:36)
        ...

````

**Comment by Guite** [comment]
Fixed in latest build (Jenkins is working on it).

**Comment by Guite** [comment]
I fear this is nothing I can easily fix.
Try starting ModuleStudio with the `-clean` argument. This might help.

**Comment by Guite** [comment]
If that does not help, try renaming `MostWorkspace` to `MostWorkspace_Backup` and check whether a fresh new workspace helps. Maybe there is something corrupt with your meta data.
