### ISSUE TITLE
Leaflet Map error with MOST 1.4.0 and Zikula 3.0.3

### ISSUE THREAD

**Issue by MisterFau** [Guite/MostGenerator#1243]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.4.0]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK30]
| Zikula Version         | [3.0.3]
| PHP Version            | [7.3]

## Expected Behavior

I generated a geographical entity. A Leflet map should appear when i use the module

## Current Behavior

No map appears.
Browser console shows:

`edit:25 GET http://www.websitename.de/modules/faumandunkwards/css/style.cssvendor/drmonty/leaflet/css/leaflet.css net::ERR_ABORTED 404 (Not Found)
2edit:2254 GET http://www.websitename.de/modules/faumandunkwards/css/style.cssvendor/drmonty/leaflet/js/leaflet.min.js net::ERR_ABORTED 404 (Not Found)
jquery.min.js:2 jQuery.Deferred exception: L is not defined ReferenceError: L is not defined
    at faumanDunkwardsInitGeographicalDisplay (http://www.websitename.de/theme/combined_asset/js/869849539abb3d8a302d685653343dbd1186400.combined.js:1249:5)
    at faumanDunkwardsInitGeographicalEditing (http://www.websitename.de/theme/combined_asset/js/869849539abb3d8a302d685653343dbd1186400.combined.js:1299:5)
    at HTMLDocument.<anonymous> (http://www.websitename.de/theme/combined_asset/js/869849539abb3d8a302d685653343dbd1186400.combined.js:1351:9)
    at e (http://www.websitename.de/jquery/jquery.min.js:2:30005)
    at t (http://www.websitename.de/jquery/jquery.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
jquery.min.js:2 Uncaught ReferenceError: L is not defined
    at faumanDunkwardsInitGeographicalDisplay (869849539abb3d8a302d685653343dbd1186400.combined.js:1249)
    at faumanDunkwardsInitGeographicalEditing (869849539abb3d8a302d685653343dbd1186400.combined.js:1299)
    at HTMLDocument.<anonymous> (869849539abb3d8a302d685653343dbd1186400.combined.js:1351)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2) (bearbeitet) `

**Comment by Guite** [comment]
Fixed in bf3c3e7fea018f7a7fc121dfe10a8543a9ae7d91
