### ISSUE TITLE
make 1.3 modules working in 1.4 environment

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#716]
pagination issue make it impossible to use 1.3.x modules for 1.4.x. 

it would be great if MOST delivers code what you suggested in https://github.com/Portugao/MUImage/issues/112 in your untested skeleton.

This feature would make it possible to create modules for 1.4 until the issue https://github.com/Guite/MostGenerator/issues/416 has been solved

**Comment by Guite** [comment]
Added in 63febb6bb14c7e20e4ec05979a280abe13d4d58a

**Comment by rallek** [comment]
Thank you! will test it soon.

**Comment by rallek** [comment]
What is the right traget I have to choose? ``zk136`` or ``zkpre14``? I want to generate a 1.3.x module wich runs under 1.4.1 or later.

**Comment by Guite** [comment]
`zk136`

**Comment by rallek** [comment]
tried ``ZK136`` without success :-(. In version it is still labled ``core_max 1.3.99``. Changing to ``1.4.99`` is not bringing success. It ends up with an error:
````
Fatal error: Class 'Gedmo\Translatable\Entity\AbstractTranslation' not found in /home/www/141.koester123.de/Zikula_Core-1.4.1/modules/VerySimplePages/lib/VerySimplePages/Entity/Base/PageTranslation.php on line 22

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(//var/lib/polkit-1): failed to open dir: Permission denied' in /home/www/141.koester123.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php:148 Stack trace: #0 [internal function]: RecursiveDirectoryIterator->__construct('//var/lib/polki...', 4096) #1 /home/www/141.koester123.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(148): RecursiveDirectoryIterator->getChildren() #2 /home/www/141.koester123.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(117): Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->findClassInPath(false, 'AbstractTransla...', 'ZikulaSecurityC...') #3 /home/www/141.koester123.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/F in /home/www/141.koester123.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php on line 148
````
I used the webgen from today. Did I something wrong?

**Comment by Guite** [comment]
This error is unrelated to the introduced paginator switch. Instead it has something to do with the translatable extension. Please create a new issue about it.

**Comment by rallek** [comment]
#721
