### ISSUE TITLE
[1.3.x] With issue 795 there is an issue with related entity

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#796]
If I try to create an entry 'movie' there is first an irritation with the dropdown list.
It is black if I click on it and the collection I have created is not there it seems.
If I click again I can choose the collection.

If I click save then, I get this error:

```
Could not load the 'muvideo' module at 'edit'.
A new entity was found through the relationship 'MUVideo_Entity_Collection#movie' that was not configured to cascade persist operations for entity: . Explicitly persist the new entity or configure cascading persist operations on the relationship. If you cannot find out which entity causes the problem implement 'MUVideo_Entity_Movie#__toString()' to get a clue.
```

Stacktrace I will provide in a few minutes.

```
#0 Ausnahmefehler in /domain/plugins/Doctrine/lib/vendor/Doctrine/ORM/UnitOfWork.php, Zeile 594
#1 /domain/plugins/Doctrine/lib/vendor/Doctrine/ORM/UnitOfWork.php(555): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(MUVideo_Entity_Collection))
#2 /domain/plugins/Doctrine/lib/vendor/Doctrine/ORM/UnitOfWork.php(261): Doctrine\ORM\UnitOfWork->computeChangeSets()
#3 /domain/plugins/Doctrine/lib/vendor/Doctrine/ORM/EntityManager.php(334): Doctrine\ORM\UnitOfWork->commit()
#4 /domain/modules/MUVideo/lib/MUVideo/Form/Handler/Common/Base/Edit.php(552): Doctrine\ORM\EntityManager->flush()
#5 /domain/modules/MUVideo/lib/MUVideo/Form/Handler/Common/Base/Edit.php(491): MUVideo_Form_Handler_Common_Base_Edit->processTranslationsForUpdate(Object(MUVideo_Entity_Movie), Array)
#6 /domain/modules/MUVideo/lib/MUVideo/Form/Handler/Movie/Base/Edit.php(164): MUVideo_Form_Handler_Common_Base_Edit->handleCommand(Object(Zikula_Form_View), Array)
#7 /domain/lib/Zikula/Form/View.php(889): MUVideo_Form_Handler_Movie_Base_Edit->handleCommand(Object(Zikula_Form_View), Array)
#8 /domain/lib/Zikula/Form/Plugin/Button.php(153): Zikula_Form_View->raiseEvent('handleCommand', Array)
#9 /domain/lib/Zikula/Form/View.php(1292): Zikula_Form_Plugin_Button->decodePostBackEvent(Object(Zikula_Form_View))
#10 /domain/lib/Zikula/Form/View.php(1291): Zikula_Form_View->decodePostBackEvent_rec(Array)
#11 /domain/lib/Zikula/Form/View.php(1278): Zikula_Form_View->decodePostBackEvent_rec(Array)
#12 /domain/lib/Zikula/Form/View.php(274): Zikula_Form_View->decodePostBackEvent()
#13 /domain/modules/MUVideo/lib/MUVideo/Controller/Base/Movie.php(342): Zikula_Form_View->execute('movie/edit.tpl', Object(MUVideo_Form_Handler_Movie_Edit))
#14 [internal function]: MUVideo_Controller_Base_Movie->edit(Array)
#15 /domain/lib/util/ModUtil.php(1110): call_user_func(Array, Array)
#16 /domain/lib/util/ModUtil.php(1192): ModUtil::exec('MUVideo', 'movie', 'edit', Array, false, NULL)
#17 /domain/modules/MUVideo/lib/MUVideo/Controller/Base/Admin.php(144): ModUtil::func('MUVideo', 'movie', 'edit', Array)
#18 [internal function]: MUVideo_Controller_Base_Admin->edit(Array)
#19 /domain/lib/util/ModUtil.php(1110): call_user_func(Array, Array)
#20 /domain/lib/util/ModUtil.php(1192): ModUtil::exec('MUVideo', 'admin', 'edit', Array, false, NULL)
#21 /domain/index.php(78): ModUtil::func('MUVideo', 'admin', 'edit', Array)
#22 {main}
```
#795

**Comment by Portugao** [comment]
If I do not choose a collection I can create an entry without an error message.

It looks like it depends on edit type. If I change form active_edit_passive_edit to active_edit_passive_chosse , it seems there is no issue....

**Comment by Guite** [comment]
As a workaround you can add a persist cascade to the relationship in the model.

**Comment by Portugao** [comment]
Should I do this in both directions?

**Comment by Guite** [comment]
Yes, I think this makes sense.

**Comment by Portugao** [comment]
Ok. Thx.

**Comment by Guite** [comment]
Postponed to 0.7.1.

**Comment by Guite** [comment]
Closed as `won't fix`.
